<?

print '

<table border="0" width="100%">
<tr class="boxtext"><td class="boxtext">
<div align=center><table border="0"><tr><td>
<pre>
                               AUCUNE GARANTIE

CE SERVICE ETANT FOURNI GRATUITEMENT SANS AUCUNE  REDEVANCE,  IL  EST 
FOURNI TEL QUEL SANS AUCUNE GARANTIE QUELLE  QU\'ELLE  SOIT,  EXPRIMÉE
OU NON, INCLUANT LES GARANTIES IMPLICITES DE COMMERCE ET D\'ADEQUATION
AVEC LE BESOIN, SANS S\'Y LIMITER. SI  LE  PROGRAMME  EST  DÉFECTUEUX,
VOUS ASSUMEZ LE COÛT DE  TOUTES  LES  RÉPARATIONS,  INTERVENTIONS  OU 
CORRECTIONS NÉCÉSSAIRES.

XNAME NE SAURAIT ÊTRE  TENU  POUR  RESPONSABLE  DES  INFORMATIONS  SE 
TROUVANT DANS LES ZONES HÉBERGÉES, NI DANS LES ZONES ELLES-MÊMES.  EN
CAS DE PLAINTE, L\'ADRESSE MÈL UTILISÉE DANS LE SOA DOIT ÊTRE UTILISÉE.
CONCERNANT LES SECONDAIRES, L\'ADRESSE MÈL UTILISÉE  POUR  ENREGISTRER
LA ZONE SERA COMMUNIQUÉE À  TOUTE  PERSONNE  LÉGALEMENT  MANDATÉE  LA
RÉCLAMANT.

CE SERVICE ÉTANT TOTALEMENT  GRATUIT,  LE  SERVICE  XNAME  PEUT  ÊTRE 
ARRÊTÉ À TOUT MOMENT, SANS  AUCUNE  FORME  DE  COMPENSATION  POSSIBLE. 
DANS  CE  CAS,  UN  AVERTISSEMENT  DE  COURTOISIE  SERA  ENVOYÉ   AUX 
UTILISATEURS DU SERVICE.

EN ENREGISTRANT UNE ZONE SUR XNAME.ORG VOUS CERTIFIEZ QUE:
- VOUS ÊTES PROPRIÉTAIRE DES ZONES QUE VOUS ENREGISTREZ,
- VOUS AVEZ LES DROITS POUR UTILISER LES DONNÉES DE VOS ENREGISTREMENTS
  (ADRESSES IP, ADRESSES MÈL, NOMS DE MACHINES, ETC...)

EN UTILISANT LE SERVICE D\'XNAME VOUS ACCEPTEZ QUE VOUS ÊTES LE SEUL
RESPONSABLE. EN CAS DE VIOLATION DE LA LOI, XNAME NE SAURAIT ÊTRE 
TENU POUR RESPONSABLE EN AUCUNE FAÇON.

</pre>
</td></tr></table></div>
</td></tr>
</table>
';

?>
