<?

print '

<table border="0" width="100%">
<tr class="boxtext"><td class="boxtext">
<div align=center><table border="0"><tr><td>
<pre>

         GWARANCJA ORAZ WARUNKI U¯YWANIA US£UGI FreeDNS::42

GWARANTUJEMY ZWROT POTRÓJNYCH KOSZTÓW U¯YWANIA TEJ US£UGI. OCZYWI¦CIE
FAKT, ¯E TEN KOSZT JEST RÓWNY 0 (s³ownie: ZERO), DO¦Æ ISTOTNIE WP£YWA
NA SUMÊ ZWROTÓW, KTÓRA JEST RÓWNA 3 * 0 = 0 (s³ownie: ZERO).
PRZY TAK NISKICH (GARD£O SOBIE PODRZYNAM) OP£ATACH ZA U¯YWANIE US£UGI
NIE JESTE¦MY W STANIE OFEROWAÆ GWARANCJI W JAKICHKOLWIEK FORMACH, ANI
WYRA¬NYCH, ANI DOMNIEMANYCH, A W SZCZEGÓLNO¦CI DOMNIEMANYCH GWARANCJI
PRZYDATNO¦CI HANDLOWEJ ALBO PRZYDATNO¦CI DO OKRE¦LONYCH CELÓW. JE¯ELI
Z£E DZIA£ANIE US£UGI NARAZI CIÊ NA KOSZTY NAPRAW LUB SERWISOWANIA, TO
POKRYJESZ TE KOSZTY WE W£ASNYM ZAKRESIE.

NIE PONIOSÊ ODPOWIEDZIALNO¦CI ZA JAKIEKOLWIEK
INFORMACJE ZAWARTE W STREFACH DNS ALBO NA SERWERACH OPISYWANYCH PRZEZ
TE STREFY. W PRZYPADKU PROBLEMU LUB ZA¯ALENIA NALE¯Y NAPISAÆ NA ADRES
ZAWARTY W REKORDZIE SOA. ADRESY E-MAIL U¯YWANE DO REJESTROWANIA STREF
MOG¡ ZOSTAÆ UJAWNIONE NA ¯¡DANIE UMOCOWANYCH OSÓB LUB INSTYTUCJI.

ZASTRZEGAM PRAWO DO WY£¡CZENIA US£UGI W CA£O¦CI LUB DOWOLNEJ CZÊ¦CI,
BEZ UPRZEDZENIA I W DOWOLNYM MOMENCIE, BEZ ¯ADNEGO ODSZKODOWANIA.

REJESTRUJ¡C STREFY W TEJ US£UDZE O¦WIADCZASZ, ¯E:
- JESTE¦ W£A¦CIELEM LUB POSIADASZ ODPOWIEDNIE PRAWA DO REJESTROWANYCH
  STREF DNS;
- POSIADASZ PRAWA DO POS£UGIWANIA SIÊ WSZYSTKIMI DANYMI UMIESZCZANYMI
  PRZEZ CIEBIE W STREFACH DNS (ADRESY IP, ADRESY E-MAIL, NAZWY);
- DYSPONUJESZ DOWODAMI POWY¯SZYCH PRAW W£ASNO¦CI LUB U¯YTKOWANIA.

PRZEZ U¯YWANIE TEJ US£UGI PRZYJMUJESZ NIEOGRANICZON¡ ODPOWIEDZIALNO¦Æ
ZA ZARZ¡DZANE PRZEZ CIEBIE STREFY DNS.

NIE PONOSZÊ ¯ADNEJ ODPOWIEDZIALNO¦CI ZA £AMANIE
PRAWA WYNIK£E Z TWOICH DZIA£AÑ LUB ICH BRAKU.

</pre>
</td></tr></table></div>
</td></tr>
</table>
';

?>
