<?

print '

<table border="0" width="100%">
<tr class="boxtext"><td class="boxtext">
<div align=center><table border="0"><tr><td>
<pre>

         GWARANCJA ORAZ WARUNKI UŻYWANIA USŁUGI FREEDNS::42

GWARANTUJEMY ZWROT POTRÓJNYCH KOSZTÓW UŻYWANIA TEJ USŁUGI. OCZYWIŚCIE
FAKT, ŻE TEN KOSZT JEST RÓWNY 0 (słownie: ZERO), DOŚĆ ISTOTNIE WPŁYWA
NA SUMĘ ZWROTÓW, KTÓRA JEST RÓWNA 3 * 0 = 0 (słownie: ZERO).
PRZY TAK NISKICH (GARDŁO SOBIE PODRZYNAM) OPŁATACH ZA UŻYWANIE USŁUGI
NIE JESTEM W STANIE OFEROWAĆ GWARANCJI W JAKICHKOLWIEK FORMACH, ANI
WYRAŹNYCH, ANI DOMNIEMANYCH, A W SZCZEGÓLNOŚCI DOMNIEMANYCH GWARANCJI
PRZYDATNOŚCI HANDLOWEJ ALBO PRZYDATNOŚCI DO OKREŚLONYCH CELÓW. JEŻELI
ZŁE DZIAŁANIE USŁUGI NARAZI CIĘ NA KOSZTY NAPRAW LUB SERWISOWANIA, TO
POKRYJESZ TE KOSZTY WE WŁASNYM ZAKRESIE.

FREEDNS::42 NIE PONIESIE ODPOWIEDZIALNOŚCI ZA JAKIEKOLWIEK
INFORMACJE ZAWARTE W STREFACH DNS ALBO NA SERWERACH OPISYWANYCH PRZEZ
TE STREFY. W PRZYPADKU PROBLEMU LUB ZAŻALENIA NALEŻY NAPISAĆ NA ADRES
ZAWARTY W REKORDZIE SOA. ADRESY E-MAIL UŻYWANE DO REJESTROWANIA STREF
MOGĄ ZOSTAĆ UJAWNIONE NA ŻĄDANIE UMOCOWANYCH OSÓB LUB INSTYTUCJI.

ZASTRZEGAM PRAWO DO WYŁĄCZENIA USŁUGI W CAŁOŚCI LUB DOWOLNEJ CZĘŚCI,
BEZ UPRZEDZENIA I W DOWOLNYM MOMENCIE, BEZ ŻADNEGO ODSZKODOWANIA.

REJESTRUJĄC STREFY W TEJ USŁUDZE OŚWIADCZASZ, ŻE:
- JESTEŚ WŁAŚCIELEM LUB POSIADASZ ODPOWIEDNIE PRAWA DO REJESTROWANYCH
  STREF DNS;
- POSIADASZ PRAWA DO POSŁUGIWANIA SIĘ WSZYSTKIMI DANYMI UMIESZCZANYMI
  PRZEZ CIEBIE W STREFACH DNS (ADRESY IP, ADRESY E-MAIL, NAZWY);
- DYSPONUJESZ DOWODAMI POWYŻSZYCH PRAW WŁASNOŚCI LUB UŻYTKOWANIA.

PRZEZ UŻYWANIE TEJ USŁUGI PRZYJMUJESZ NIEOGRANICZONĄ ODPOWIEDZIALNOŚĆ
ZA ZARZĄDZANE PRZEZ CIEBIE STREFY DNS.

FREEDNS::42 NIE PONOSI ŻADNEJ ODPOWIEDZIALNOŚCI ZA ŁAMANIE
PRAWA WYNIKŁE Z TWOICH DZIAŁAŃ LUB ICH BRAKU.

</pre>
</td></tr></table></div>
</td></tr>
</table>
';

?>
